cleanup.yml
Just got started with Ansible today. I'm also not experienced with Kubernetes (outside of minikube) yet. Anyway, while studying your script(s), I noticed that the `etcdctl` binary wasn't cleaned up. Unless it shouldn't be, for some reason? :)
=> Remove the `etcdctl` binary when cleaning up

roles/etcd/templates/etcd.service.j2
I was getting an error when starting etcd (it was running successfully, though, as far as I could see):
```
Dec 14 14:05:34 kubernetesmaster01 etcd[31989]: forgot to set Type=notify in systemd service file?
```
With this change, I can start up etcd without any errors in the logs.
=> Set systemd service type to `notify` for `etcd`

cleanup.yml
The following is now cleaned up as expected:
* `/usr/local/bin/kube-proxy` (binary on workers)
* `/etc/systemd/system/kube-apiserver.service` (systemd unit file on masters)
* `/etc/systemd/system/kube-controller-manager.service` (systemd unit file on masters)
* `/etc/systemd/system/kube-scheduler.service` (systemd unit file on masters)
* `/etc/kubernetes` (config and SSL on masters)
=> Improve cleanup playbook

README.md
I'm not sure you want something like this in the README, it's just a suggestion.
I'm also not sure if it's actually useful to separate each Kubernetes component (I assume they should always be the same version?).
Another thing: do you have any insight of what it would mean to bump versions? For example, if I wanted to run the latest version of Kubernetes instead (`v1.13.1` as of writing this), what would that mean for the other versions (etcd, containerd, runc, cni)?
=> Add version matrix

README.md, roles/certificates/tasks/main.yml, roles/etcd/tasks/main.yml, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml
This is useful if you have multiple clusters whose hostnames all start with the same part, for example:
```
k8s.service.office.local
k8s.service.production.local
```
With this fix, I could call my clusters `stage` and `production` (where the `stage` cluster would be running on the office domain, while the `production` cluster would be running in the production domain).
=> Suggestion: Allow overriding the cluster name

roles/certificates/templates/openssl.conf.j2
This might not be the way to go, this is just a suggestion up for discussion. The point is that I'd like to be able to access the cluster using a specific hostname of one of the masters.
Background:
I'd like to specify a specific hostname for my clusters, for example `k8s.service.office.local` (where `office.local` is the domain). This hostname is load balanced against all masters, right? However, I haven't decided how I want to load balance it yet. I was thinking of using the nginx **within** the cluster (if possible, I haven't checked that out yet) to load balance the masters themselves. To be able to set up my NGINX Ingress Controller in my new cluster, I must be able to access it with `kubectl`, which I can't do yet, since the load balanced domain isn't actually working yet. …
=> Suggestion: Individual master hostnames in SSL certificate

cleanup.yml
Closes #16 
This **might** leave a "broken" `current-context` in your kubeconfig, if you have currently selected the context that is being removed. However, I thought that was better than unsetting the value in case you'd have another context selected already. The effect of this would be:
```
➜ kubectl get pods --all-namespaces
Error in configuration: context was not found for specified context: <cluster_name>
```
=> Clean up local kubeconfig

cleanup.yml
Closes #12
I decided to "replace" the existing task for unmounting `/var/lib/kubelet` because I think this new one does the trick for everything. But if it's not, let me know and I'll put it back.
=> Properly unmount directories in `/var/lib/kubelet`

cleanup.yml
Looks like this binary is new in containerd 1.2, see contents of `https://github.com/containerd/containerd/releases/download/v1.2.1/containerd-1.2.1.linux-amd64.tar.gz`.
=> Remove `containerd-shim-runc-v1` as well when cleaning up

install.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-controller-manager/templates/kube-controller-manager.kubeconfig, roles/kube-proxy/tasks/main.yml, roles/kube-proxy/templates/kube-proxy.kubeconfig, roles/kube-scheduler/tasks/main.yml, roles/kube-scheduler/templates/kube-scheduler.kubeconfig, roles/kubelet/tasks/main.yml, roles/kubelet/templates/node.kubeconfig
Closes #22 
There was a mix of `hostvars[item].inventory_hostname` and `inventory_hostname` in a task that had `run_once: True`, causing it to give all nodes the hostname of the first node in the credentials part of kubeconfig.
Here's an example kubeconfig of my `k8s-worker-02` before this fix:
```yaml
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: <redacted>
server: https://k8s-master-01:6443
name: kubernetes
contexts:
- context:
cluster: kubernetes
user: system:node:k8s-worker-02
name: default
current-context: default
kind: Config
preferences: {}
users:
- name: system:node:k8s-worker-01
user:
client-certificate-data: <redacted>
client-key-data: <redacted>
```
=> Use the correct hostname in kubelet's kubeconfig

roles/kube-controller-manager/templates/kube-controller-manager.service.j2
Removed flags from kube-controller-manager which uses the defaults anyway
=> Use default flags to kube-controller-manager

roles/kube-scheduler/templates/kube-scheduler.service.j2
Removed flags from kube-scheduler which uses the defaults anyway
=> Use default flags to kube-scheduler

README.md, roles/kube-apiserver/tasks/main.yml, roles/kube-apiserver/templates/kube-apiserver.service.j2
This replaces `enable_admission_plugins`. I don't think this complicates things more than `enable_admission_plugins` used to do, and I can very easily add whatever options I want, like this:
```
[all:vars]
custom_options_apiserver=--enable-admission-plugins=PodSecurityPolicy --oidc-issuer-url=https://dex.svc.example.local --oidc-client-id=loginapp --oidc-ca-file=/etc/kubernetes/pki/custom-ca.crt --oidc-username-claim=email --oidc-groups-claim=groups
```
Closes #37
=> Allow dynamic configuration of `kube-apiserver`

roles/kube-apiserver/templates/kube-apiserver.service.j2
Removed `--` from service unit file template for `kube-apiserver`. I think it makes more sense to the user and also allows for shorthand flags.
=> Remove kube_apiserver double dash from template

README.md, roles/cni/tasks/main.yml, roles/containerd/tasks/main.yml, roles/etcd/tasks/main.yml, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
Updates components to
* `Kubernetes 1.14.0`
* `cni 0.6.0`
* `containerd 1.2.1`
Was unable to successfully update `runc` to `1.0.0-rc7` due to https://github.com/opencontainers/runc/pull/2031
Fixes #41
=> Update component versions

README.md, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
I never upgraded from `1.13.1` to `1.14.0`, i went straight to `1.14.1` using the changes of this pull request.
I do want to highlight that it didn't go as smooth as I'd like. Everything went as expected until the end of the playbook. My NGINX ingress controllers all went down for a short period. I have a hard time figuring out why.
I see these events in my NGINX ingress controller pods:
```
Warning  Unhealthy  7m23s  kubelet, k8s-nginx-11  Readiness probe failed: HTTP probe failed with statuscode: 500
```
And I see logs like this from the pods:
```
Received SIGTERM, shutting down
k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:153: watch of *v1.Service ended with: too old resource version: 18603171 (18603183)
```
I believe the `SIGTERM` comes from the readiness probe …
=> Bump Kubernetes versions to `1.14.1`

install.yml, roles/containerd/handlers/main.yml, roles/containerd/tasks/main.yml, roles/etcd/handlers/main.yml, roles/etcd/tasks/main.yml, roles/kube-apiserver/handlers/main.yml, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/handlers/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/handlers/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/handlers/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/handlers/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
This PR adds [Handlers](https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change) to those roles that have servers that needs to be restarted at the end of each play. Namely:
* containerd
* kubelet
* kube-apiserver
* kube-scheduler
* kube-controller-manager
=> Restart services with handlers

.travis.yml, README.md, install.yml, roles/etcd/tasks/main.yml, roles/kube-apiserver/tasks/main.yml
This way, we won't stop for example the API server or `kube-proxy` on all
masters or nodes at the same time, causing downtime.
To do:
Discussions:
* Are the delays and timeouts OK? 5 second before start checking, then check each second and timeout after 30 seconds.
* Should these be configurable with Ansible parameters?
=> Make sure upgrades are sequential

README.md, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
All components are updated which includes:
* kube-apiserver
* kube-scheduler
* kube-controller-manager
* kube-proxy
* kubelet
* kubectl (for testing only)
Fixes #55
=> Bump Kubernetes to v1.14.4

README.md, roles/containerd/tasks/main.yml, roles/containerd/templates/config.toml.j2, roles/runc/tasks/main.yml
Update containerd's configuration so that it does not contain any deprecated options. See https://github.com/containerd/cri/blob/release/1.2/docs/config.md
In later versions of containerd the config has changed again and needs to be updated again. Will be included in the next release
=> Update containerd `config.toml` with non-deprecated config

README.md, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
> CNI remains unchanged at v0.7.5. (kubernetes/kubernetes#75455)
We have v0.7.5 already, so we're fine.
> Default etcd server version remains unchanged at v3.3.10. The etcd client version was updated to v3.3.10. (kubernetes/kubernetes#71615, kubernetes/kubernetes#70168, kubernetes/kubernetes#76917)
We have v3.3.12, so we must be fine! :)
I haven't found any service options that we use that has been deprecated.
=> Bump Kubernetes to v1.15.10

README.md, install.yml, roles/crictl/tasks/main.yml
Closes #64
I decided to not have this configurable for now. We can always change this if the need arises.
I also decided to use version 1.16, since we have a PR for Kubernetes 1.16 anyway (#65).
=> Install `crictl` on nodes

README.md, roles/etcd/tasks/main.yml, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, test/main.yml
> CNI remains unchanged at v0.7.5. (kubernetes/kubernetes#75455)
We have v0.7.5 already, so we're fine.
> etcd has been updated to v3.3.15 (kubernetes/kubernetes#82199, @ dims)
We currently have v3.3.12. I've bumped to v3.3.15 in this PR.
I haven't found any service options that we use that has been deprecated.
=> Bump Kubernetes to v1.16.7

roles/containerd/templates/containerd.service.j2
The entry `TasksMax=infinity` in `/etc/systemd/system/containerd.service` will prevent nodes from failing to run containers due to too many processes max limit. 
This parameters exists in the official [containerd/cri](https://github.com/containerd/cri) version of containerd.service: https://github.com/containerd/cri/blob/master/contrib/systemd-units/containerd.service
=> Add `TasksMax=infinity` to `containerd.service`

.travis.yml, README.md, roles/kube-apiserver/tasks/main.yml, roles/kube-controller-manager/tasks/main.yml, roles/kube-proxy/tasks/main.yml, roles/kube-scheduler/tasks/main.yml, roles/kubelet/tasks/main.yml, roles/runc/tasks/main.yml, test/main.yml
When I upgraded one of my clusters that were utilizing `flannel` to 1.16.7 which is the latest KTRW, I hit this issue:
https://github.com/kubernetes/kubernetes/pull/92035
We use a temporary fix on our worker nodes. This real fix has been backported to a later 1.16 version, so I'd be great with this bump. I'd love this "fixed" for the cluster before I proceed to bumping to 1.17.
I figured we could create the patch release `v1.2.1` with this commit included. If you agree, do you think that the other commit since `v1.2.0` (98aac409d35731239c4eb7418dba63697045d882) should be included too?
=> Bump Kubernetes to v1.16.13
